version: '3.5'
services:
  es-1:
    image: elasticsearch:7.6.2
    container_name: es-1
    networks: 
      - default
    environment:
      - node.name=es-1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-2,es-3
      - cluster.initial_master_nodes=es-1,es-2,es-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/1/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  es-2:
    image: elasticsearch:7.6.2
    container_name: es-2
    networks: 
      - default
    environment:
      - node.name=es-2
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-1,es-3
      - cluster.initial_master_nodes=es-1,es-2,es-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/2/data:/usr/share/elasticsearch/data

  es-3:
    image: elasticsearch:7.6.2
    container_name: es-3
    networks: 
      - default
    environment:
      - node.name=es-3
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-1,es-2
      - cluster.initial_master_nodes=es-1,es-2,es-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/3/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.6.2
    container_name: kibana
    networks: 
      - default
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://es-0:9200
      # - ELASTICSEARCH_HOSTS=http://es-0:9200

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6
    networks: 
      - default
    ports:
      - "2181:2181"

  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:5.4.1
    networks: 
      - default
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_NO: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"

  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:5.4.1
    networks: 
      - default
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_NO: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"

  kafka-3:
    container_name: kafka-3
    image: confluentinc/cp-kafka:5.4.1
    networks: 
      - default
    ports:
      - "9094:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_NO: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"

  kafka-manager:
    container_name: kafka-manager
    image: kafkamanager/kafka-manager
    networks: 
      - default
    links: 
      - zookeeper:zookeeper
    ports: 
      - 9000:9000
    depends_on: 
      - zookeeper
    environment: 
      - ZK_HOSTS=zookeeper:2181

  logstash:
    container_name: logstash
    image: logstash:7.6.2
    depends_on: 
      - es-1
      - es-2
      - es-3
    networks: 
      - default
    ports: 
      - 5044:5044/tcp
      - 9600:9600/tcp
    volumes: 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  filebeat:
    container_name: filebeat
    image: store/elastic/filebeat:7.6.2
    networks: 
      - default
    depends_on: 
      - kafka-1
      - kafka-2
      - kafka-3
      - logstash
    volumes: 
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/usr/share/filebeat/logs/

networks: 
  default:
    driver: bridge